//
// Copyright 2020 Electronic Arts Inc.
//
// TiberianDawn.DLL and RedAlert.dll and corresponding source code is free 
// software: you can redistribute it and/or modify it under the terms of 
// the GNU General Public License as published by the Free Software Foundation, 
// either version 3 of the License, or (at your option) any later version.

// TiberianDawn.DLL and RedAlert.dll and corresponding source code is distributed 
// in the hope that it will be useful, but with permitted additional restrictions 
// under Section 7 of the GPL. See the GNU General Public License in LICENSE.TXT 
// distributed with this program. You should have received a copy of the 
// GNU General Public License along with permitted additional restrictions 
// with this program. If not, see https://github.com/electronicarts/CnC_Remastered_Collection

//	Wolstrng.h - this will presumably go away eventually.

//	New character strings.

extern const char TXT_WOL_INTERNETBUTTON[];
extern const char TXT_WOL_ERRORMESSAGE[];
extern const char TXT_WOL_CONNECT[];
extern const char TXT_WOL_LOGINDIALOG[];
extern const char TXT_WOL_NAME[];
extern const char TXT_WOL_PASSWORD[];
extern const char TXT_WOL_SAVELOGIN[];
extern const char TXT_WOL_LOGINCANCEL[];
extern const char TXT_WOL_MISSINGNAME[];
extern const char TXT_WOL_MISSINGPASSWORD[];
extern const char TXT_WOL_CANTSAVENICK[];
extern const char TXT_WOL_NICKINUSE[];
extern const char TXT_WOL_BADPASS[];
extern const char TXT_WOL_TIMEOUT[];
extern const char TXT_WOL_CONNECTING[];
extern const char TXT_WOL_CANTCONNECT[];
extern const char TXT_WOL_ATTEMPTLOGIN[];
extern const char TXT_WOL_ATTEMPTLOGOUT[];
extern const char TXT_WOL_ERRORLOGOUT[];
extern const char TXT_WOL_WAIT[];
extern const char TXT_WOL_OFFICIALCHAT[];
extern const char TXT_WOL_USERCHAT[];
extern const char TXT_WOL_YOURENOTINCHANNEL[];
extern const char TXT_WOL_ACTION[];
extern const char TXT_WOL_JOIN[];
extern const char TXT_WOL_CANTCREATEINCHANNEL[];
extern const char TXT_WOL_NEWSOMETHING[];
extern const char TXT_WOL_CREATECHANNELTITLE[];
extern const char TXT_WOL_CREATECHANNELPROMPT[];
extern const char TXT_WOL_PASSPROMPT[];
extern const char TXT_WOL_OPTIONALPASSPROMPT[];
extern const char TXT_WOL_CHANNEL_TOP[];
extern const char TXT_WOL_CHANNEL_BACK[];
extern const char TXT_WOL_YOUJOINED[];
extern const char TXT_WOL_YOUJOINEDGAME[];
extern const char TXT_WOL_YOUCREATEDGAME[];
extern const char TXT_WOL_YOUJOINEDLOBBY[];
extern const char TXT_WOL_YOULEFT[];
extern const char TXT_WOL_YOULEFTLOBBY[];
extern const char TXT_WOL_JOINPRIVATETITLE[];
extern const char TXT_WOL_JOINPRIVATEPROMPT[];
extern const char TXT_WOL_BADCHANKEY[];
extern const char TXT_WOL_PAGELOCATE[];
extern const char TXT_WOL_USERNAMEPROMPT[];
extern const char TXT_WOL_PAGE[];
extern const char TXT_WOL_LOCATE[];
extern const char TXT_WOL_LOCATING[];
extern const char TXT_WOL_FIND_NOTHERE[];
extern const char TXT_WOL_FIND_NOCHAN[];
extern const char TXT_WOL_FIND_OFF[];
extern const char TXT_WOL_FOUNDIN[];
extern const char TXT_WOL_PAGEMESSAGETITLE[];
extern const char TXT_WOL_PAGEMESSAGEPROMPT[];
extern const char TXT_WOL_PAGING[];
extern const char TXT_WOL_PAGE_NOTHERE[];
extern const char TXT_WOL_PAGE_OFF[];
extern const char TXT_WOL_ONPAGE[];
extern const char TXT_WOL_WASPAGED[];
//extern const char TXT_WOL_USERISSQUELCHED[];
//extern const char TXT_WOL_USERISNOTSQUELCHED[];
extern const char TXT_WOL_ONLYOWNERCANKICK[];
extern const char TXT_WOL_USERKICKEDUSER[];
extern const char TXT_WOL_USERKICKEDYOU[];
extern const char TXT_WOL_NOONETOKICK[];
extern const char TXT_WOL_USERWASBANNED[];
extern const char TXT_WOL_GAMECHANNELS[];
extern const char TXT_WOL_CHANNELLISTLOADING[];
extern const char TXT_WOL_CREATEPRIVGAMETITLE[];
extern const char TXT_WOL_YOUREBANNED[];
extern const char TXT_WOL_PLAYERLEFTGAME[];
extern const char TXT_WOL_PLAYERJOINEDGAME[];
extern const char TXT_WOL_YOUWEREKICKEDFROMGAME[];
extern const char TXT_WOL_PERSONALWINLOSSRECORD[];
extern const char TXT_WOL_PERSONALWINLOSSRECORDAM[];
extern const char TXT_WOL_USERRANK[];
extern const char TXT_WOL_USERHOUSE[];
extern const char TXT_WOL_USERRANKHOUSE[];
extern const char TXT_WOL_STARTBUTTON[];
extern const char TXT_WOL_ACCEPTBUTTON[];
extern const char TXT_WOL_HOSTLEFTGAME[];
extern const char TXT_WOL_WAITINGTOSTART[];
extern const char TXT_WOL_TTIP_DISCON[];
extern const char TXT_WOL_TTIP_LEAVE[];
extern const char TXT_WOL_TTIP_REFRESH[];
extern const char TXT_WOL_TTIP_SQUELCH[];
extern const char TXT_WOL_TTIP_BAN[];
extern const char TXT_WOL_TTIP_KICK[];
extern const char TXT_WOL_TTIP_FINDPAGE[];
extern const char TXT_WOL_TTIP_OPTIONS[];
extern const char TXT_WOL_TTIP_LADDER[];
extern const char TXT_WOL_TTIP_HELP[];
extern const char TXT_WOL_TTIP_START[];
extern const char TXT_WOL_TTIP_ACCEPT[];
extern const char TXT_WOL_TTIP_EXPANDLIST[];
extern const char TXT_WOL_TTIP_CANCELGAME[];
extern const char TXT_WOL_TTIP_JOIN[];
extern const char TXT_WOL_TTIP_BACK[];
extern const char TXT_WOL_TTIP_CREATE[];
extern const char TXT_WOL_TTIP_ACTION[];
extern const char TXT_WOL_OPTFIND[];
extern const char TXT_WOL_OPTPAGE[];
extern const char TXT_WOL_OPTLANGUAGE[];
extern const char TXT_WOL_OPTGAMESCOPE[];
extern const char TXT_WOL_OPTTITLE[];
extern const char TXT_WOL_REDALERTLOBBIES[];
extern const char TXT_WOL_TOPLEVELTITLE[];
extern const char TXT_WOL_CHANNELGONE[];
extern const char TXT_WOL_CG_TITLE[];
extern const char TXT_WOL_CG_PLAYERS[];
extern const char TXT_WOL_CG_TOURNAMENT[];
extern const char TXT_WOL_CG_PRIVACY[];
extern const char TXT_WOL_CG_RAGAME[];
extern const char TXT_WOL_CG_CSGAME[];
extern const char TXT_WOL_CG_AMGAME[];
extern const char TXT_WOL_NEEDCOUNTERSTRIKE[];
extern const char TXT_WOL_NEEDAFTERMATH[];
extern const char TXT_WOL_TTIP_CHANLIST_CHAT[];
extern const char TXT_WOL_TTIP_CHANLIST_LOBBY[];
extern const char TXT_WOL_TTIP_REDALERT[];
extern const char TXT_WOL_TTIP_COUNTERSTRIKE[];
extern const char TXT_WOL_TTIP_AFTERMATH[];
extern const char TXT_WOL_TTIP_CHANLIST_RAGAME[];
extern const char TXT_WOL_TTIP_CHANLIST_GAME[];
extern const char TXT_WOL_TTIP_PRIVATEGAME[];
extern const char TXT_WOL_TTIP_TOURNAMENTGAME[];
extern const char TXT_WOL_TTIP_CHANNELTYPE_GAMESOFTYPE[];
extern const char TXT_WOL_TOURNAMENTPLAYERLIMIT[];
extern const char TXT_WOL_PRIVATEPASSWORD[];
extern const char TXT_WOL_RULESMISMATCH[];
extern const char TXT_WOL_STARTTIMEOUT[];
extern const char TXT_WOL_CANCELGAME[];
extern const char TXT_WOL_PATCHQUESTION[];
extern const char TXT_WOL_DOWNLOADING[];
extern const char TXT_WOL_DOWNLOADERROR[];
extern const char TXT_WOL_DOWNLOADBYTES[];
extern const char TXT_WOL_DOWNLOADTIME[];
extern const char TXT_WOL_DOWNLOADRESUMED[];
extern const char TXT_WOL_DOWNLOADCONNECTING[];
extern const char TXT_WOL_DOWNLOADLOCATING[];
extern const char TXT_WOL_DOWNLOADDOWNLOADING[];
extern const char TXT_WOL_DOWNLOADEXITWARNING[];
extern const char TXT_WOL_HELPSHELL[];
extern const char TXT_WOL_LADDERSHELL[];
extern const char TXT_WOL_WEBREGISTRATIONSHELL[];
extern const char TXT_WOL_GAMEADVERTSHELL[];
extern const char TXT_WOL_USERLIST[];
extern const char TXT_WOL_NOUSERLIST[];
extern const char TXT_WOL_STARTCANCELLED[];
extern const char TXT_WOL_CANTCREATEHERE[];
extern const char TXT_WOL_WOLAPIGONE[];
extern const char TXT_WOL_WOLAPIREINIT[];
extern const char TXT_WOL_NOTPAGED[];
extern const char TXT_WOL_SCENARIONAMEWAIT[];
extern const char TXT_WOL_BACK[];
extern const char TXT_WOL_AMDISCNEEDED[];
extern const char TXT_WOL_CONFIRMLOGOUT[];
extern const char TXT_WOL_PROPOSE_DRAW[];
extern const char TXT_WOL_RETRACT_DRAW[];
extern const char TXT_WOL_ACCEPT_DRAW[];
extern const char TXT_WOL_PROPOSE_DRAW_CONFIRM[];
extern const char TXT_WOL_ACCEPT_DRAW_CONFIRM[];
extern const char TXT_WOL_DRAW_PROPOSED_LOCAL[];
extern const char TXT_WOL_DRAW_PROPOSED_OTHER[];
extern const char TXT_WOL_DRAW_RETRACTED_LOCAL[];
extern const char TXT_WOL_DRAW_RETRACTED_OTHER[];
extern const char TXT_WOL_DRAW[];
extern const char TXT_WOL_CANTLAUNCHBROWSER[];
extern const char TXT_WOL_CHANNELFULL[];
extern const char TXT_WOL_CHANNELTYPE_TOP[];
extern const char TXT_WOL_CHANNELTYPE_OFFICIALCHAT[];
extern const char TXT_WOL_CHANNELTYPE_USERCHAT[];
extern const char TXT_WOL_CHANNELTYPE_GAMES[];
extern const char TXT_WOL_CHANNELTYPE_LOADING[];
extern const char TXT_WOL_CHANNELTYPE_LOBBIES[];
extern const char TXT_WOL_FINDINGLOBBY[];
extern const char TXT_WOL_PRIVATETOMULTIPLE[];
extern const char TXT_WOL_PRIVATETO[];
extern const char TXT_WOL_CS_MISSIONS[];
extern const char TXT_WOL_AM_MISSIONS[];
extern const char TXT_WOL_CANTSQUELCHSELF[];
extern const char TXT_WOL_SLOWUNITBUILD[];
extern const char TXT_WOL_THEGAMEHOST[];
extern const char TXT_WOL_TTIP_RANKRA[];
extern const char TXT_WOL_TTIP_RANKAM[];
extern const char TXT_WOL_OPTRANKAM[];
extern const char TXT_WOL_CANCELMEANSFORFEIT[];
extern const char TXT_WOL_DLLERROR_GETIE3[];
extern const char TXT_WOL_DLLERROR_CALLUS[];
extern const char TXT_WOL_PRIVATE[];

